[build]
  publish = "build"
  command = "npm run build:production"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-v2/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"
  
  external_node_modules = ["@mongodb-js/saslprep", "mongodb", "bcrypt"]